### PR TITLE
Quick build cleanup

### PR DESCRIPTION
**Pull request by adamdecaf**
Hey! I saw you're asking for a maintainer so I took a look at this image. I've never used helpy before, but it looks pretty useful! 

Things I fixed quick:
- The tag version was wrong. [1.1.0 was released not 1.1](https://github.com/helpyio/helpy/releases/tag/1.1.0)
- Clone helpyio_slack over https: [Docs](https://bundler.io/git.html)

There are some other fixes I can see right off the bat. 
- The image builds at ~1gb, which is really big. I think we could trim this down.
- No automated build. Docker hub has a free automated builds for open source projects. 
  - Example: https://github.com/adamdecaf/docker-znc
- Older versions
  - It looks like [some versions of deps are old](https://github.com/helpyio/helpy/issues/224) (running on ruby 2.2). I could help upgrade the container and deps. I'm not really a ruby dev, but I can work the basics. 

Issue: https://github.com/helpyio/helpy/issues/469

### CODE REVIEW

**Comment by scott** [comment]
Hi @adamdecaf this is awesome!  Any additional help you can offer would be much appreciated.

**Comment by adamdecaf** [comment]
@scott Would you guys mind creating a docker hub organization and adding me? I can setup an automated build off master.

My Account: https://hub.docker.com/r/adamdecaf/

**Comment by scott** [comment]
Yes for sure.

**Comment by scott** [comment]
Okay you should be in.  Looks like one guy already did this, but its an older version https://hub.docker.com/r/derdiedasjojo/helpyio-docker/

**Comment by adamdecaf** [comment]
@scott Weird. I can't seem to make an automated build. I think I need to be part of the github org. If you want to it's [filling out this form](https://hub.docker.com/add/automated-build/helpy/). 

BTW is there a slack/gitter to join?

**Pull request merged**
